name: qiraati
description: Qiraati - aplikasi belajar Iqro
publish_to: "none"
version: 1.0.0+1  

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.2.3  
  audioplayers: ^5.0.1
  syncfusion_flutter_pdfviewer: ^22.1.36
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/pdf/iqro_jilid1.pdf
    - assets/pdf/iqro_jilid2.pdf
    - assets/pdf/iqro_jilid3.pdf
    - assets/pdf/iqro_jilid4.pdf
    - assets/pdf/iqro_jilid5.pdf
    - assets/pdf/iqro_jilid6.pdf
    - assets/audio/
    - assets/data/
    - assets/profile/profile.png
