// lib/screens/asmaul_husna_screen.dart
import 'package:flutter/material.dart';

class AsmaulHusnaScreen extends StatelessWidget {
  const AsmaulHusnaScreen({super.key});

  final List<Map<String, String>> _asmaulHusna = const 
    [
  {"arab": "الرَّحْمَنُ", "arti": "Yang Maha Pengasih"},
  {"arab": "الرَّحِيمُ", "arti": "Yang Maha Penyayang"},
  {"arab": "الْمَلِكُ", "arti": "Yang Maha Merajai"},
  {"arab": "الْقُدُّوسُ", "arti": "Yang Maha Suci"},
  {"arab": "السَّلاَمُ", "arti": "Yang Maha Pemberi Kedamaian"},
  {"arab": "الْمُؤْمِنُ", "arti": "Yang Maha Memberi Keamanan"},
  {"arab": "الْمُهَيْمِنُ", "arti": "Yang Maha Mengawasi"},
  {"arab": "الْعَزِيزُ", "arti": "Yang Maha Perkasa"},
  {"arab": "الْجَبَّارُ", "arti": "Yang Maha Kuasa"},
  {"arab": "الْمُتَكَبِّرُ", "arti": "Yang Maha Megah"},
  {"arab": "الْخَالِقُ", "arti": "Yang Maha Pencipta"},
  {"arab": "الْبَارِئُ", "arti": "Yang Maha Melepaskan"},
  {"arab": "الْمُصَوِّرُ", "arti": "Yang Maha Membentuk Rupa"},
  {"arab": "الْغَفَّارُ", "arti": "Yang Maha Pengampun"},
  {"arab": "الْقَهَّارُ", "arti": "Yang Maha Memaksa"},
  {"arab": "الْوَهَّابُ", "arti": "Yang Maha Pemberi Karunia"},
  {"arab": "الرَّزَّاقُ", "arti": "Yang Maha Pemberi Rezeki"},
  {"arab": "الْفَتَّاحُ", "arti": "Yang Maha Pembuka Rahmat"},
  {"arab": "اَلْعَلِيْمُ", "arti": "Yang Maha Mengetahui"},
  {"arab": "الْقَابِضُ", "arti": "Yang Maha Menyempitkan"},
  {"arab": "الْبَاسِطُ", "arti": "Yang Maha Melapangkan"},
  {"arab": "الْخَافِضُ", "arti": "Yang Maha Merendahkan"},
  {"arab": "الرَّافِعُ", "arti": "Yang Maha Meninggikan"},
  {"arab": "الْمُعِزُّ", "arti": "Yang Maha Memuliakan"},
  {"arab": "المُذِلُّ", "arti": "Yang Maha Menghinakan"},
  {"arab": "السَّمِيعُ", "arti": "Yang Maha Mendengar"},
  {"arab": "الْبَصِيرُ", "arti": "Yang Maha Melihat"},
  {"arab": "الْحَكَمُ", "arti": "Yang Maha Menetapkan"},
  {"arab": "الْعَدْلُ", "arti": "Yang Maha Adil"},
  {"arab": "اللَّطِيفُ", "arti": "Yang Maha Lembut"},
  {"arab": "الْخَبِيرُ", "arti": "Yang Maha Mengetahui Rahasia"},
  {"arab": "الْحَلِيمُ", "arti": "Yang Maha Penyantun"},
  {"arab": "الْعَظِيمُ", "arti": "Yang Maha Agung"},
  {"arab": "الْغَفُورُ", "arti": "Yang Maha Pengampun"},
  {"arab": "الشَّكُورُ", "arti": "Yang Maha Pembalas Budi"},
  {"arab": "الْعَلِيُّ", "arti": "Yang Maha Tinggi"},
  {"arab": "الْكَبِيرُ", "arti": "Yang Maha Besar"},
  {"arab": "الْحَفِيظُ", "arti": "Yang Maha Memelihara"},
  {"arab": "المُقِيتُ", "arti": "Yang Maha Pemberi Kecukupan"},
  {"arab": "الْحسِيبُ", "arti": "Yang Maha Membuat Perhitungan"},
  {"arab": "الْجَلِيلُ", "arti": "Yang Maha Mulia"},
  {"arab": "الْكَرِيمُ", "arti": "Yang Maha Mulia"},
  {"arab": "الرَّقِيبُ", "arti": "Yang Maha Mengawasi"},
  {"arab": "الْمُجِيبُ", "arti": "Yang Maha Mengabulkan"},
  {"arab": "الْوَاسِعُ", "arti": "Yang Maha Luas"},
  {"arab": "الْحَكِيمُ", "arti": "Yang Maha Bijaksana"},
  {"arab": "الْوَدُودُ", "arti": "Yang Maha Mengasihi"},
  {"arab": "الْمَجِيدُ", "arti": "Yang Maha Mulia"},
  {"arab": "الْبَاعِثُ", "arti": "Yang Maha Membangkitkan"},
  {"arab": "الشَّهِيدُ", "arti": "Yang Maha Menyaksikan"},
  {"arab": "الْحَقُ", "arti": "Yang Maha Benar"},
  {"arab": "الْوَكِيلُ", "arti": "Yang Maha Memelihara"},
  {"arab": "الْقَوِيُ", "arti": "Yang Maha Kuat"},
  {"arab": "الْمَتِينُ", "arti": "Yang Maha Kokoh"},
  {"arab": "الْوَلِيُّ", "arti": "Yang Maha Melindungi"},
  {"arab": "الْحَمِيدُ", "arti": "Yang Maha Terpuji"},
  {"arab": "الْمُحْصِي", "arti": "Yang Maha Menghitung"},
  {"arab": "الْمُبْدِئُ", "arti": "Yang Maha Memulai"},
  {"arab": "الْمُعِيدُ", "arti": "Yang Maha Mengembalikan Kehidupan"},
  {"arab": "الْمُحْيِي", "arti": "Yang Maha Menghidupkan"},
  {"arab": "اَلْمُمِيتُ", "arti": "Yang Maha Mematikan"},
  {"arab": "الْحَيُّ", "arti": "Yang Maha Hidup"},
  {"arab": "الْقَيُّومُ", "arti": "Yang Maha Mandiri"},
  {"arab": "الْوَاجِدُ", "arti": "Yang Maha Penemu"},
  {"arab": "الْمَاجِدُ", "arti": "Yang Maha Mulia"},
  {"arab": "الْواحِدُ", "arti": "Yang Maha Tunggal"},
  {"arab": "اَلاَحَدُ", "arti": "Yang Maha Esa"},
  {"arab": "الصَّمَدُ", "arti": "Yang Maha Dibutuhkan"},
  {"arab": "الْقَادِرُ", "arti": "Yang Maha Menentukan"},
  {"arab": "الْمُقْتَدِرُ", "arti": "Yang Maha Berkuasa"},
  {"arab": "الْمُقَدِّمُ", "arti": "Yang Maha Mendahulukan"},
  {"arab": "الْمُؤَخِّرُ", "arti": "Yang Maha Mengakhirkan"},
  {"arab": "الأوَّلُ", "arti": "Yang Maha Awal"},
  {"arab": "الآخِرُ", "arti": "Yang Maha Akhir"},
  {"arab": "الظَّاهِرُ", "arti": "Yang Maha Nyata"},
  {"arab": "الْبَاطِنُ", "arti": "Yang Maha Ghaib"},
  {"arab": "الْوَالِي", "arti": "Yang Maha Memerintah"},
  {"arab": "الْمُتَعَالِي", "arti": "Yang Maha Tinggi"},
  {"arab": "الْبَرُّ", "arti": "Yang Maha Dermawan"},
  {"arab": "التَّوَابُ", "arti": "Yang Maha Penerima Tobat"},
  {"arab": "الْمُنْتَقِمُ", "arti": "Yang Maha Pemberi Balasan"},
  {"arab": "العَفُو", "arti": "Yang Maha Pemaaf"},
  {"arab": "الرَّؤُوفُ", "arti": "Yang Maha Pengasuh"},
  {"arab": "مَالِكُ الْمُلْكِ", "arti": "Yang Maha Penguasa Kerajaan"},
  {"arab": "ذُوالْجَلاَلِ وَالإكْرَامِ", "arti": "Yang Maha Pemilik Kebesaran dan Kemuliaan"},
  {"arab": "الْمُقْسِطُ", "arti": "Yang Maha Pemberi Keadilan"},
  {"arab": "الْجَامِعُ", "arti": "Yang Maha Mengumpulkan"},
  {"arab": "الْغَنيُ", "arti": "Yang Maha Kaya"},
  {"arab": "الْمُغْنِي", "arti": "Yang Maha Pemberi Kekayaan"},
  {"arab": "اَلْمَانِعُ", "arti": "Yang Maha Mencegah"},
  {"arab": "الضَّارَ", "arti": "Yang Maha Memberi Derita"},
  {"arab": "النَّافِعُ", "arti": "Yang Maha Memberi Manfaat"},
  {"arab": "النُّورُ", "arti": "Yang Maha Bercahaya"},
  {"arab": "الْهَادِي", "arti": "Yang Maha Pemberi Petunjuk"},
  {"arab": "الْبَدِيعُ", "arti": "Yang Maha Pencipta"},
  {"arab": "اَلْبَاقِي", "arti": "Yang Maha Kekal"},
  {"arab": "الْوَارِثُ", "arti": "Yang Maha Pewaris"},
  {"arab": "الرَّشِيدُ", "arti": "Yang Maha Pandai"},
  {"arab": "الصَّبُورُ", "arti": "Yang Maha Penyabar"}

  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("Asmaul Husna")),
      body: GridView.builder(
        padding: const EdgeInsets.all(12),
        gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
          crossAxisCount: 2,
          crossAxisSpacing: 10,
          mainAxisSpacing: 10,
          childAspectRatio: 1.3,
        ),
        itemCount: _asmaulHusna.length,
        itemBuilder: (_, i) {
          final item = _asmaulHusna[i];
          return InkWell(
            child: Ink(
              decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(12),
                border: Border.all(color: Colors.green.shade100),
              ),
              child: Padding(
                padding: const EdgeInsets.all(8),
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Text(item['arab']!,
                        textAlign: TextAlign.center,
                        style: const TextStyle(fontSize: 20)),
                    const SizedBox(height: 6),
                    Text(item['arti']!,
                        textAlign: TextAlign.center,
                        style: const TextStyle(fontSize: 14)),
                  ],
                ),
              ),
            ),
          );
        },
      ),
    );
  }
}
